// app/api/map/feisean/route.js
// Fèisean & Highland Games as map pins. Joins the static ASGF festival list
// (FESTIVALS) with its geocoded coordinates (FEIS_COORDS, generated by the
// scratchpad geocoder) and returns one pin per game that has coords.
//
// This is public data — it's the same list rendered on the public /feisean
// page — so no auth. The personal globe reads it for every signed-in user
// (so the games appear on everyone's globe), and /saoghal can use the same
// endpoint later.

import { FESTIVALS } from '../../../(main)/feisean/data';
import { FEIS_COORDS } from '../../../(main)/feisean/coords';

export const runtime = 'nodejs';

export async function GET() {
  const feisean = FESTIVALS
    .map((f) => {
      const c = FEIS_COORDS[f.id];
      if (!c) return null;
      return {
        id: f.id,
        name: f.name,
        city: f.city,
        state: f.state,
        dateDisplay: f.date_display || null,
        website: f.website || null,
        lat: c.lat,
        lng: c.lng,
      };
    })
    .filter(Boolean);

  return Response.json({ ok: true, feisean });
}
