// Seed list for the Gàidhlig diaspora place-name map.
//
// EVERY entry below should be reviewed by a native Gàidhlig speaker before
// publishing widely. The `verified` flag drives a small "unverified — help us
// confirm" badge in the side panel, so unverified entries are still useful but
// honestly flagged.
//
// Adding a place: drop a new object in the array. The map re-renders from this
// list — no other code changes needed.

export const PLACES = [
  {
    id: 'perth-ny',
    name: 'Perth',
    region: 'New York, USA',
    lng: -74.1707,
    lat: 43.0084,
    gaidhlig: 'Peairt',
    meaning: 'From a Pictish root meaning "wood" or "copse"; later associated with the thorn-bush.',
    why_named: 'Named after Perth, Scotland by Scottish settlers who arrived in the late 18th century.',
    founded: '1779',
    verified: false,
  },
  {
    id: 'broadalbin-ny',
    name: 'Broadalbin',
    region: 'New York, USA',
    lng: -74.1965,
    lat: 43.0640,
    gaidhlig: 'Bràghad Albann',
    meaning: '"The uplands of Alba (Scotland)" — the highland country.',
    why_named: 'Named after the Breadalbane region of Perthshire by emigrants from that area.',
    founded: '1815',
    verified: false,
  },
  {
    id: 'argyle-ny',
    name: 'Argyle',
    region: 'New York, USA',
    lng: -73.4948,
    lat: 43.2425,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"The coastland of the Gaels."',
    why_named: 'Named for Argyll, the ancestral kingdom of Dál Riata. Settled by Scottish Presbyterians in the 18th century.',
    founded: '1764',
    verified: false,
  },
  {
    id: 'scotia-ny',
    name: 'Scotia',
    region: 'New York, USA',
    lng: -73.9651,
    lat: 42.8267,
    gaidhlig: 'Alba',
    meaning: 'Scotia is the medieval Latin name for Scotland; the Gàidhlig name is Alba.',
    why_named: 'Named by Alexander Glen in 1658 in honour of his Scottish homeland.',
    founded: '1658',
    verified: false,
  },
  {
    id: 'inverness-ns',
    name: 'Inverness',
    region: 'Nova Scotia, Canada',
    lng: -61.2926,
    lat: 46.2336,
    gaidhlig: 'Inbhir Nis',
    meaning: '"Mouth of the River Ness."',
    why_named: 'Named for Inverness, the Highland capital, by Cape Breton settlers from the Scottish Highlands.',
    founded: '~1803',
    verified: false,
  },
  {
    id: 'glencoe-on',
    name: 'Glencoe',
    region: 'Ontario, Canada',
    lng: -81.7059,
    lat: 42.7501,
    gaidhlig: 'Gleann Comhann',
    meaning: '"The glen of the River Coe" — the glen of the 1692 massacre.',
    why_named: 'Settled in the 1830s by Highland Scots remembering the original Glen Coe.',
    founded: '~1836',
    verified: false,
  },
  {
    id: 'kilmarnock-va',
    name: 'Kilmarnock',
    region: 'Virginia, USA',
    lng: -76.3791,
    lat: 37.7115,
    gaidhlig: 'Cill Mheàrnaig',
    meaning: '"The church of (Saint) Marnoc" — a 7th-century Celtic saint.',
    why_named: 'Named for Kilmarnock in Ayrshire, Scotland.',
    founded: '~1780',
    verified: false,
  },
  {
    id: 'islay-township-on',
    name: 'Islay Township',
    region: 'Ontario, Canada',
    lng: -83.5,
    lat: 46.7,
    gaidhlig: 'Ìle',
    meaning: 'Pre-Celtic origin, uncertain; possibly meaning "swelling" or "island flank."',
    why_named: 'Named for the Hebridean island of Islay.',
    founded: null,
    verified: false,
  },
  {
    id: 'benbecula-ns',
    name: 'Benbecula',
    region: 'Nova Scotia, Canada',
    lng: -60.85,
    lat: 46.05,
    gaidhlig: 'Beinn nam Faoghla',
    meaning: '"Mountain of the fords" — referring to the tidal fords linking the islands.',
    why_named: 'Named after the Outer Hebridean island of Benbecula.',
    founded: null,
    verified: false,
  },
  {
    id: 'ballachulish-oh',
    name: 'Ballachulish',
    region: 'Ohio, USA',
    lng: -82.0,
    lat: 40.4,
    gaidhlig: "Baile a' Chaolais",
    meaning: '"Settlement of the narrows."',
    why_named: 'Named for Ballachulish in Argyllshire, at the mouth of Loch Leven.',
    founded: null,
    verified: false,
  },
  {
    id: 'argyle-wi',
    name: 'Argyle',
    region: 'Wisconsin, USA',
    lng: -89.8664,
    lat: 42.7018,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"The coastland of the Gaels."',
    why_named: 'Settled in the 1840s by Scottish lead-miners moving up from the Galena district; named for Argyll.',
    founded: '~1844',
    verified: false,
    body_en: `Far a bheil thu / Where you are
You're in the Driftless Area of southwestern Wisconsin — rolling, unglaciated hill country in Lafayette County. The village of Argyle sits on the East Branch of the Pecatonica River and is best known today as the boyhood home of Robert M. LaFollette. Your neighbors' heritage here is a patchwork: Norwegian and Cornish names dominate the county records, with a strong Irish presence too. Argyle's Scottish thread is narrower, but it's distinct — and it's the reason this village carries a Highland name in the middle of Norwegian dairy country.

Na tha mu do choinneamh / What's around you
The nearest living Scottish cultural calendar runs through the Milwaukee–Waukesha corridor, about 80–100 miles east:

- Milwaukee Highland Games — held each June at Croatian Park in Franklin, WI.
- Wisconsin Highland Games — the larger of the two, held over Labor Day weekend at the Waukesha County Expo, run by Wisconsin Scottish Inc. It includes a clan tent area, genealogy resources, piping and drumming competitions, and Highland dance.

For research into the families themselves, the Wisconsin Historical Society (headquartered in Madison, about 40 miles northeast) holds the state's principal genealogical archive, and Lafayette County's own local history societies keep records specific to the original township plats.

For learning the language: there is currently no active Scottish Gàidhlig program at either UW–Madison or UW–Milwaukee. UW–Madison runs community classes in Irish Gaelic, and UW–Milwaukee's Celtic Studies Center is also Irish-focused. For Scottish Gàidhlig itself, the realistic starting points from Argyle are online: [GlobalCeilidh.com](https://globalceilidh.com), [Colaisde na Gàidhlig](https://gaeliccollege.edu) (the Gaelic College in St. Ann's, Cape Breton), and [ACGA](https://acgamerica.org) (An Comunn Gàidhlig Ameireaganach — the North American Gaelic society).

Mar a ràinig thu an seo / How you got here
Argyle exists because of one man's gratitude. Allan Wright, a Scottish immigrant, settled at a ford on the Pecatonica River in the 1840s and was appointed the settlement's first postmaster in 1844. He named the new post office Argyle after the Duke of Argyll, who had financially sponsored his passage from Scotland.

Wright's arrival became an anchor point for a small, tightly bound group of families. His sister Helen married Allen Mitchell, a Paisley shawl weaver by trade, who staked land near the river in 1847, drawn west by the regional lead-mining boom. When more Scottish families arrived — the Arnots, from the Firth of Forth area, and the Pattersons — they crowded into the Mitchell home together while their own houses were built, a pattern typical of how small Highland and Lowland-Scots beachheads took root across the American frontier.

By 1850, New England settlers had partnered with this original Scottish core to formally plat Argyle's streets — the village's civic shape from the very start was a joint Scottish–Yankee project.

A' Ghàidhlig an seo / Gàidhlig here
Gàidhlig did not take root in Argyle. Unlike the larger, longer-lived Gaelic-speaking communities of places like North Carolina or Nova Scotia, the Argyle settlers were too few, and assimilated too fast, to sustain the language across generations. There were no Gàidhlig churches, newspapers, or schools here — the language likely fell silent within one or two generations of arrival. There is no revival community in Argyle today. The nearest path back to the language runs through the wider region or online, not through any local institution.`,
    body_gd: `Far a bheil thu
Tha thu ann an sgìre Driftless ann an iar-dheas Wisconsin — dùthaich chnocach, gun eigh-shruth, ann an Siorrachd Lafayette. Tha am baile beag Argyle na laighe air Meur an Ear de dh'Abhainn Pecatonica, agus tha e ainmeil an-diugh mar dhachaigh òigridh Robert M. LaFollette. Tha dualchas do choimhearsnaich an seo measgaichte — Nirribheach is Còrnach gu mòr, le buaidh Èireannach làidir cuideachd. Tha an snàithlean Albannach ann an Argyle na chaolas, ach tha e sònraichte — agus is e sin as coireach gu bheil ainm Gàidhealach air a' bhaile am meadhan dùthaich na Nirribhich.

Na tha mu do choinneamh
Tha am mìosachan cultarail Albannach as fhaisge a' ruith tro sgìre Milwaukee-Waukesha, mu 80–100 mìle an ear:

- Geamannan Gàidhealach Milwaukee — anns an Ògmhios gach bliadhna, aig Croatian Park, Franklin, WI.
- Geamannan Gàidhealach Wisconsin — am fear as motha dhiubh, air an cumail thairis air deireadh-seachdain Latha an Luchd-obrach aig Ionad-falbhain Siorrachd Waukesha.

Airson rannsachadh teaghlaich, tha Comann Eachdraidh Wisconsin ann am Madison na phrìomh tasglann sloinntearachd na stàite.

Airson an cànan ionnsachadh: chan eil prògram beò Gàidhlig na h-Alba an-dràsta aig Oilthigh Wisconsin-Madison no Milwaukee — chan eil ann ach Gaeilge na h-Èireann. Airson Gàidhlig na h-Alba fhèin, 's e na puingean tòiseachaidh as practaigiche bho Argyle: [GlobalCeilidh.com](https://globalceilidh.com), [Colaisde na Gàidhlig](https://gaeliccollege.edu) (an Colaisde Ghàidhlig ann an Cidhe Anna, Eilean Cheap Breatainn), agus [ACGA](https://acgamerica.org) (An Comunn Gàidhlig Ameireaganach).

Mar a ràinig thu an seo
Tha Argyle ann air sgàth taingealachd aon duine. Shocraich Allan Wright, eilthireach Albannach, aig àth air Abhainn Pecatonica anns na 1840an, agus chaidh a chur an dreuchd mar phost-mhaighstir an toiseach ann an 1844. Thug e Argyle mar ainm air an oifis-puist ùr, an dèidh Diùc Earra-Ghàidheal, a phàigh airson a thurais bhon Alba.

Thàinig teaghlaichean eile — na Arnotaich, à sgìre Linne Foirthe, agus na Pattersonaich — agus chaidh iad uile a-steach do dhachaigh nan Mitchell gus an deach an taighean fhèin a thogail.

Ro 1850, bha luchd-tuineachaidh à Sasainn Nuadh air com-pàirteachadh leis an teaghlaichean Albannach tùsail seo gus sràidean Argyle a dhealbhadh gu foirmeil.

A' Ghàidhlig an seo
Cha do ghabh a' Ghàidhlig freumh ann an Argyle. An àite na coimhearsnachdan Gàidhlig nas motha agus nas maireannaiche ann an àiteachan mar North Carolina no Alba Nuadh, bha an fheadhainn a thuinich ann an Argyle ro bheag an àireamh, agus ro luath gan co-mheasgachadh, gus an cànan a chumail beò thar ginealaichean. Cha robh eaglaisean, pàipearan-naidheachd, no sgoiltean Gàidhlig ann an seo — is dòcha gun do thuit an cànan sàmhach taobh a-staigh aon no dhà ghinealach às dèidh dhaibh ruighinn. Chan eil coimhearsnachd ath-bheothachaidh ann an Argyle an-diugh. Tha an t-slighe as fhaisge air ais chun a' chànain a' dol tron sgìre nas fharsainge no air loidhne, chan ann tro institiud ionadail sam bith.`,
  },
  {
    id: 'caledonia-wi',
    name: 'Caledonia',
    region: 'Wisconsin, USA',
    lng: -89.51417,
    lat: 43.48361,
    gaidhlig: 'Alba',
    meaning: 'Caledonia is the Latin name the Romans gave to Scotland; the Gàidhlig name for the country is Alba.',
    why_named: 'A settlers\' tribute to the Scottish homeland — one of several Caledonias scattered across the diaspora.',
    founded: '1839',
    verified: false,
  },
  {
    id: 'glencoe-mn',
    name: 'Glencoe',
    region: 'Minnesota, USA',
    lng: -94.1517,
    lat: 44.7691,
    gaidhlig: 'Gleann Comhann',
    meaning: '"The glen of the River Coe" — the glen of the 1692 massacre.',
    why_named: 'Named in 1855 for Glen Coe in Scotland by founding settler Martin McLeod.',
    founded: '1855',
    verified: false,
  },
  {
    id: 'inverness-ca',
    name: 'Inverness',
    region: 'California, USA',
    lng: -122.8580,
    lat: 38.1010,
    gaidhlig: 'Inbhir Nis',
    meaning: '"Mouth of the River Ness."',
    why_named: 'Founded on Tomales Bay in 1889 by James Shafter, a Scottish-American attorney who said the landscape reminded him of the Highlands.',
    founded: '1889',
    verified: false,
  },
  {
    id: 'glengarry-on',
    name: 'Glengarry',
    region: 'Ontario, Canada',
    lng: -74.6400,
    lat: 45.3800,
    gaidhlig: 'Gleann Garadh',
    meaning: '"The glen of the River Garry."',
    why_named: 'Named for Glen Garry in Inverness-shire, the seat of Clann Dòmhnaill of Glengarry. Settled from 1784 onward by Highland Loyalists who came up from the Mohawk Valley, then by waves of direct emigrants from Knoydart and Glengarry itself — the densest Gàidhlig-speaking county in 19th-century Canada.',
    founded: '1784',
    verified: false,
  },
  {
    id: 'iona-ns',
    name: 'Iona',
    region: 'Nova Scotia, Canada',
    lng: -60.7937,
    lat: 45.9603,
    gaidhlig: 'Ì (Ì Chaluim Chille)',
    meaning: '"The (yew) island" — the second form means "Iona of Columba" after the saint.',
    why_named: "Named for the holy isle of Iona off Mull, the cradle of Gaelic Christianity. Sits on the Bras d'Or Lake at the heart of Cape Breton's Gàidhlig-speaking belt; home to the Highland Village Museum / Baile nan Gàidheal.",
    founded: '~1820s',
    verified: false,
  },

  // ────────────────────────────────────────────────────────────────
  // US — Alabama through Michigan
  // First batch from the Gàidhlig-named US towns doc (2026-06-20).
  // All entries verified: false pending native-speaker review.
  // ────────────────────────────────────────────────────────────────

  // Alabama
  {
    id: 'lenox-al',
    name: 'Lenox',
    region: 'Alabama, USA',
    lng: -86.9869,
    lat: 31.2898,
    gaidhlig: 'Leamhnach',
    meaning: '"Leamhnach" — "place of elms" (leamhan); the Gàidhlig name for the Lennox region around Loch Lomond.',
    why_named: 'Named for the Lennox region of Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcintosh-al',
    name: 'McIntosh',
    region: 'Alabama, USA',
    lng: -88.0264,
    lat: 31.2649,
    gaidhlig: 'Baile ’ic an Tòisich',
    meaning: '"Settlement of MacIntosh" — Mac an Tòisich, "son of the chief."',
    why_named: 'Named for the McIntosh family who settled the area.',
    founded: null,
    verified: false,
  },
  {
    id: 'mckenzie-al',
    name: 'McKenzie',
    region: 'Alabama, USA',
    lng: -86.7141,
    lat: 31.5388,
    gaidhlig: 'Baile ’icCoinnich',
    meaning: '"Settlement of MacKenzie" — Mac Coinnich, "son of Coinneach (Kenneth)."',
    why_named: 'Named for the MacKenzie family.',
    founded: null,
    verified: false,
  },

  // Alaska
  {
    id: 'houston-ak',
    name: 'Houston',
    region: 'Alaska, USA',
    lng: -149.8181,
    lat: 61.6306,
    gaidhlig: 'Baile Eòghainn',
    meaning: '"Settlement of Eòghann (Hugh / Ewan)" — the Gàidhlig rendering of the surname Houston.',
    why_named: 'Named for Sam Houston of Texas; the Houston surname descends from Houston in Renfrewshire, Scotland.',
    founded: '1966',
    verified: false,
  },
  {
    id: 'point-mackenzie-ak',
    name: 'Point MacKenzie',
    region: 'Alaska, USA',
    lng: -149.9678,
    lat: 61.2375,
    gaidhlig: 'Rubha ’icCoinnich',
    meaning: '"Point of MacKenzie" — rubha = headland / point.',
    why_named: 'Named for Alexander Mackenzie, the Scottish-born fur trader and explorer.',
    founded: null,
    verified: false,
  },

  // Arizona
  {
    id: 'elgin-az',
    name: 'Elgin',
    region: 'Arizona, USA',
    lng: -110.5223,
    lat: 31.6336,
    gaidhlig: 'Eilginn',
    meaning: '"Eilginn" — possibly a Pictish root, sometimes glossed as "little Ireland."',
    why_named: 'Named for Elgin in Moray, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'glendale-az',
    name: 'Glendale',
    region: 'Arizona, USA',
    lng: -112.1860,
    lat: 33.5387,
    gaidhlig: 'Gleann Dail',
    meaning: '"Gleann Dail" — "glen of the dale / meadow."',
    why_named: 'Named in the Scottish "Glen-" pattern by founder William J. Murphy.',
    founded: '1892',
    verified: false,
  },

  // Arkansas
  {
    id: 'mcdougal-ar',
    name: 'McDougal',
    region: 'Arkansas, USA',
    lng: -90.4034,
    lat: 36.4631,
    gaidhlig: 'Baile ’icDhùghaill',
    meaning: '"Settlement of MacDougall" — Mac Dhùghaill, "son of Dùghall (the dark stranger)."',
    why_named: 'Named for the MacDougall family.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcnab-ar',
    name: 'McNab',
    region: 'Arkansas, USA',
    lng: -93.8327,
    lat: 33.8540,
    gaidhlig: 'Baile ’ic an Aba',
    meaning: '"Settlement of MacNab" — Mac an Aba, "son of the abbot."',
    why_named: 'Named for the MacNab family / Clan MacNab.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcneil-ar',
    name: 'McNeil',
    region: 'Arkansas, USA',
    lng: -93.2102,
    lat: 33.3460,
    gaidhlig: 'Baile ’icNìll',
    meaning: '"Settlement of MacNeil" — Mac Nèill, "son of Niall (Neil)."',
    why_named: 'Named for the MacNeil family.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcrae-ar',
    name: 'McRae',
    region: 'Arkansas, USA',
    lng: -91.8246,
    lat: 35.1196,
    gaidhlig: 'Baile ’icRàth',
    meaning: '"Settlement of MacRae" — Mac Ràth, "son of grace / fortune."',
    why_named: 'Named for the MacRae family.',
    founded: null,
    verified: false,
  },

  // California — Inverness, CA already on the map as inverness-ca
  {
    id: 'albany-ca',
    name: 'Albany',
    region: 'California, USA',
    lng: -122.2978,
    lat: 37.8869,
    gaidhlig: 'Alba',
    meaning: 'Alba is the Gàidhlig name for Scotland; Albany comes from the Latinised form.',
    why_named: 'Named in 1908 for Albany, NY — itself a tribute to the Duke of Albany.',
    founded: '1908',
    verified: false,
  },
  {
    id: 'loch-lomond-ca',
    name: 'Loch Lomond',
    region: 'California, USA',
    lng: -122.1380,
    lat: 37.0908,
    gaidhlig: 'Loch Laomainn',
    meaning: '"Loch Laomainn" — possibly "the beacon loch" or "loch of the elms."',
    why_named: 'Named for Loch Lomond, Scotland; a reservoir in the Santa Cruz Mountains.',
    founded: null,
    verified: false,
  },

  // Colorado
  {
    id: 'gleneagle-co',
    name: 'Gleneagle',
    region: 'Colorado, USA',
    lng: -104.8327,
    lat: 39.0731,
    gaidhlig: 'Gleann na h-Eaglais',
    meaning: '"Gleann na h-Eaglais" — "the glen of the church"; Scottish Gleneagles is often "glen of notches."',
    why_named: 'Named after Gleneagles in Perthshire, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'lochbuie-co',
    name: 'Lochbuie',
    region: 'Colorado, USA',
    lng: -104.7158,
    lat: 39.9908,
    gaidhlig: 'Loch Buidhe',
    meaning: '"Loch Buidhe" — "the yellow loch."',
    why_named: 'Named for Lochbuie on the Isle of Mull.',
    founded: null,
    verified: false,
  },
  {
    id: 'sterling-co',
    name: 'Sterling',
    region: 'Colorado, USA',
    lng: -103.2077,
    lat: 40.6256,
    gaidhlig: 'Sruighlea',
    meaning: '"Sruighlea" is the Gàidhlig name for Stirling.',
    why_named: 'Named for Sterling, Illinois — which in turn echoes Stirling, Scotland.',
    founded: '1881',
    verified: false,
  },

  // Connecticut
  {
    id: 'scotland-ct',
    name: 'Scotland',
    region: 'Connecticut, USA',
    lng: -72.0925,
    lat: 41.6967,
    gaidhlig: 'Alba',
    meaning: 'Alba is the Gàidhlig name for Scotland.',
    why_named: 'Named by Isaac Magoon, a Scottish settler who arrived in 1700, in tribute to his homeland.',
    founded: '1700',
    verified: false,
  },

  // Delaware
  {
    id: 'dunleith-de',
    name: 'Dunleith',
    region: 'Delaware, USA',
    lng: -75.5891,
    lat: 39.7345,
    gaidhlig: 'Dùn Leith',
    meaning: '"Dùn Leith" — "fort of Leith" or "grey fort."',
    why_named: 'Named in the Scottish style after Leith / Dunleith.',
    founded: null,
    verified: false,
  },
  {
    id: 'glasgow-de',
    name: 'Glasgow',
    region: 'Delaware, USA',
    lng: -75.7460,
    lat: 39.6017,
    gaidhlig: 'Glaschu',
    meaning: '"Glaschu" — traditionally "dear green place"; the older root is likely "green hollow."',
    why_named: 'Named for Glasgow, Scotland.',
    founded: null,
    verified: false,
  },

  // District of Columbia
  {
    id: 'douglass-dc',
    name: 'Douglass',
    region: 'Washington, D.C., USA',
    lng: -76.9881,
    lat: 38.8636,
    gaidhlig: 'Dùbhghlas',
    meaning: '"Dùbhghlas" — "dark stream" (dubh + glas), the source of the surname Douglas.',
    why_named: 'Anacostia / Frederick Douglass area — named for the abolitionist, whose surname descends from the Scottish Clan Douglas.',
    founded: null,
    verified: false,
  },
  {
    id: 'dunbar-dc',
    name: 'Dunbar',
    region: 'Washington, D.C., USA',
    lng: -77.0117,
    lat: 38.9079,
    gaidhlig: 'Dùn Bàrr',
    meaning: '"Dùn Bàrr" — "fort on the summit / point."',
    why_named: 'Named after Dunbar in East Lothian, Scotland (by way of poet Paul Laurence Dunbar).',
    founded: null,
    verified: false,
  },

  // Florida
  {
    id: 'aberdeen-fl',
    name: 'Aberdeen',
    region: 'Florida, USA',
    lng: -80.1278,
    lat: 26.5379,
    gaidhlig: 'Obar Dheathain',
    meaning: '"Obar Dheathain" — "mouth of the Don" (obar = confluence; Don = river name).',
    why_named: 'Named for Aberdeen, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'dundee-fl',
    name: 'Dundee',
    region: 'Florida, USA',
    lng: -81.6231,
    lat: 28.0205,
    gaidhlig: 'Dùn Dé',
    meaning: '"Dùn Dé" — possibly "fort of the Tay" or "fort of God."',
    why_named: 'Named for Dundee, Scotland.',
    founded: '1924',
    verified: false,
  },
  {
    id: 'dunedin-fl',
    name: 'Dunedin',
    region: 'Florida, USA',
    lng: -82.7723,
    lat: 28.0197,
    gaidhlig: 'Dùn Èideann',
    meaning: '"Dùn Èideann" is the Gàidhlig name for Edinburgh — "fort of Eidyn."',
    why_named: 'Named in 1882 by Scottish settlers J.O. Douglas and James Somerville after Edinburgh, Scotland.',
    founded: '1882',
    verified: false,
  },
  {
    id: 'fort-lauderdale-fl',
    name: 'Fort Lauderdale',
    region: 'Florida, USA',
    lng: -80.1373,
    lat: 26.1224,
    gaidhlig: 'Dùn Shrath Labhdair',
    meaning: '"Dùn Shrath Labhdair" — a Gàidhlig rendering: "fort of the strath of Lauder."',
    why_named: 'Named for Major William Lauderdale, who built forts in the area during the Second Seminole War (1838).',
    founded: '1838',
    verified: false,
  },

  // Georgia
  {
    id: 'albany-ga',
    name: 'Albany',
    region: 'Georgia, USA',
    lng: -84.1557,
    lat: 31.5785,
    gaidhlig: 'Alba',
    meaning: 'Alba is the Gàidhlig name for Scotland.',
    why_named: 'Named for Albany, NY — ultimately a tribute to the Duke of Albany / Scotland.',
    founded: '1836',
    verified: false,
  },
  {
    id: 'argyle-ga',
    name: 'Argyle',
    region: 'Georgia, USA',
    lng: -82.6126,
    lat: 30.9633,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"Earra-Ghàidheal" — "the coastland of the Gaels."',
    why_named: 'Named for Argyll, the ancestral kingdom of Dál Riata.',
    founded: null,
    verified: false,
  },
  {
    id: 'clyde-ga',
    name: 'Clyde',
    region: 'Georgia, USA',
    lng: -81.31,
    lat: 32.13,
    gaidhlig: 'Cluaidh',
    meaning: '"Cluaidh" — the river name, possibly "the cleansing one."',
    why_named: 'Named for the River Clyde, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'culloden-ga',
    name: 'Culloden',
    region: 'Georgia, USA',
    lng: -84.0938,
    lat: 32.8593,
    gaidhlig: 'Cùl-Lodair',
    meaning: '"Cùl-Lodair" — "the nook of the marsh" (cùl = back / nook; lodair = marshy place).',
    why_named: 'Named after Culloden, where the 1746 Jacobite rising ended.',
    founded: '1812',
    verified: false,
  },

  // Idaho
  {
    id: 'drummond-id',
    name: 'Drummond',
    region: 'Idaho, USA',
    lng: -111.6700,
    lat: 43.7866,
    gaidhlig: 'Dromain',
    meaning: '"Dromain" — "ridge / place on the ridge" (druim = ridge).',
    why_named: 'Named after the Drummond family / Drummond, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'mccall-id',
    name: 'McCall',
    region: 'Idaho, USA',
    lng: -116.0986,
    lat: 44.9111,
    gaidhlig: 'Baile ’icColla',
    meaning: '"Settlement of MacColl" — Mac Colla, "son of Coll."',
    why_named: 'Named for Tom McCall, who founded the town in 1889.',
    founded: '1889',
    verified: false,
  },
  {
    id: 'wallace-id',
    name: 'Wallace',
    region: 'Idaho, USA',
    lng: -115.9242,
    lat: 47.4732,
    gaidhlig: 'Uallas',
    meaning: '"Uallas" — the Gàidhlig rendering of Wallace; from "wealh," "foreigner / Briton."',
    why_named: 'Named for Colonel W.R. Wallace, who founded the silver-mining camp in 1884.',
    founded: '1884',
    verified: false,
  },

  // Illinois
  {
    id: 'dunfermline-il',
    name: 'Dunfermline',
    region: 'Illinois, USA',
    lng: -90.0026,
    lat: 40.5562,
    gaidhlig: 'Dùn Phàrlain',
    meaning: '"Dùn Phàrlain" — Pharlan\'s fort (a personal-name origin).',
    why_named: 'Named for Dunfermline in Fife, ancient capital of the Scottish kings.',
    founded: '1834',
    verified: false,
  },
  {
    id: 'glencoe-il',
    name: 'Glencoe',
    region: 'Illinois, USA',
    lng: -87.7589,
    lat: 42.1378,
    gaidhlig: 'Gleann Comhainn',
    meaning: '"Gleann Comhainn" — "the glen of the River Coe."',
    why_named: 'Named for Glen Coe in Scotland.',
    founded: '1869',
    verified: false,
  },
  {
    id: 'lanark-il',
    name: 'Lanark',
    region: 'Illinois, USA',
    lng: -89.8345,
    lat: 42.1028,
    gaidhlig: 'Lannraig',
    meaning: '"Lannraig" — from a Brittonic root meaning "glade / clear space."',
    why_named: 'Named for Lanark, Scotland.',
    founded: '1861',
    verified: false,
  },

  // Iowa
  {
    id: 'angus-ia',
    name: 'Angus',
    region: 'Iowa, USA',
    lng: -94.1583,
    lat: 41.9286,
    gaidhlig: 'Aonghas',
    meaning: '"Aonghas" — "one choice" (aon + ghus); also the name of the Scottish region.',
    why_named: 'Named for Angus / Aonghas in Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'berwick-ia',
    name: 'Berwick',
    region: 'Iowa, USA',
    lng: -93.5277,
    lat: 41.6494,
    gaidhlig: 'Baraig',
    meaning: '"Baraig" — Gàidhlig rendering of Berwick (Old English "bere-wic," "barley farm").',
    why_named: 'Named for Berwick in the Scottish Borders / Berwickshire.',
    founded: null,
    verified: false,
  },
  {
    id: 'harris-ia',
    name: 'Harris',
    region: 'Iowa, USA',
    lng: -95.4347,
    lat: 43.4413,
    gaidhlig: 'Na Hearadh',
    meaning: '"Na Hearadh" — the Outer Hebridean island of Harris; possibly "high ground."',
    why_named: 'Named for the Hebridean island of Harris.',
    founded: null,
    verified: false,
  },
  {
    id: 'lewis-ia',
    name: 'Lewis',
    region: 'Iowa, USA',
    lng: -95.0768,
    lat: 41.3105,
    gaidhlig: 'Leòdhas',
    meaning: '"Leòdhas" — the Outer Hebridean island of Lewis; origin uncertain (possibly "marshy place").',
    why_named: 'Named for the Hebridean island of Lewis.',
    founded: null,
    verified: false,
  },
  {
    id: 'melrose-ia',
    name: 'Melrose',
    region: 'Iowa, USA',
    lng: -93.0541,
    lat: 40.9806,
    gaidhlig: 'Maol Ros',
    meaning: '"Maol Ros" — "the bare promontory."',
    why_named: 'Named for Melrose in the Scottish Borders.',
    founded: null,
    verified: false,
  },

  // Kansas
  {
    id: 'athol-ks',
    name: 'Athol',
    region: 'Kansas, USA',
    lng: -98.9197,
    lat: 39.7681,
    gaidhlig: 'Athall',
    meaning: '"Athall" — Atholl, a region of Perthshire; possibly "new Ireland" (Ath + Fhódla).',
    why_named: 'Named for Atholl in Perthshire, Scotland.',
    founded: null,
    verified: false,
  },

  // Kentucky
  {
    id: 'aberdeen-ky',
    name: 'Aberdeen',
    region: 'Kentucky, USA',
    lng: -86.9686,
    lat: 37.2531,
    gaidhlig: 'Obar Dheathain',
    meaning: '"Obar Dheathain" — "mouth of the Don."',
    why_named: 'Named for Aberdeen, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'glasgow-ky',
    name: 'Glasgow',
    region: 'Kentucky, USA',
    lng: -85.9117,
    lat: 37.0014,
    gaidhlig: 'Glaschu',
    meaning: '"Glaschu" — traditionally "dear green place"; root likely "green hollow."',
    why_named: 'Named for Glasgow, Scotland.',
    founded: '1799',
    verified: false,
  },
  {
    id: 'glencoe-ky',
    name: 'Glencoe',
    region: 'Kentucky, USA',
    lng: -84.8175,
    lat: 38.7028,
    gaidhlig: 'Gleann Comhainn',
    meaning: '"Gleann Comhainn" — "the glen of the River Coe."',
    why_named: 'Named for Glen Coe in Scotland.',
    founded: null,
    verified: false,
  },

  // Louisiana
  {
    id: 'albany-la',
    name: 'Albany',
    region: 'Louisiana, USA',
    lng: -90.5854,
    lat: 30.5083,
    gaidhlig: 'Alba',
    meaning: 'Alba is the Gàidhlig name for Scotland.',
    why_named: 'A diaspora tribute to Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'henderson-la',
    name: 'Henderson',
    region: 'Louisiana, USA',
    lng: -91.7965,
    lat: 30.3149,
    gaidhlig: 'Baile ’icEanruig',
    meaning: '"Settlement of Henderson" — Mac Eanruig, "son of Henry."',
    why_named: 'Named for the Henderson family.',
    founded: null,
    verified: false,
  },
  {
    id: 'livingston-la',
    name: 'Livingston',
    region: 'Louisiana, USA',
    lng: -90.7479,
    lat: 30.5019,
    gaidhlig: 'Baile DhuinnShléibhe',
    meaning: '"Baile DhuinnShléibhe" — Gàidhlig rendering: "settlement of the brown hill / Dunsleve."',
    why_named: 'Named for the Livingston family, of Scottish Livingston origin.',
    founded: null,
    verified: false,
  },

  // Maine
  {
    id: 'north-berwick-me',
    name: 'North Berwick',
    region: 'Maine, USA',
    lng: -70.7339,
    lat: 43.3015,
    gaidhlig: 'Baraig a Tuath',
    meaning: '"Baraig a Tuath" — "North Berwick" (a tuath = of the north).',
    why_named: 'Named for North Berwick in East Lothian, Scotland.',
    founded: null,
    verified: false,
  },

  // Maryland
  {
    id: 'glenelg-md',
    name: 'Glenelg',
    region: 'Maryland, USA',
    lng: -77.0006,
    lat: 39.2331,
    gaidhlig: 'Gleann Eilg',
    meaning: '"Gleann Eilg" — "the glen of Eilg," an older Gaelic name for Ireland.',
    why_named: 'Named for Glenelg in Lochalsh, Scottish Highlands.',
    founded: null,
    verified: false,
  },
  {
    id: 'lochearn-md',
    name: 'Lochearn',
    region: 'Maryland, USA',
    lng: -76.7397,
    lat: 39.3284,
    gaidhlig: 'Loch Éireann',
    meaning: '"Loch Éireann" — the loch named for an Èireann / personal name.',
    why_named: 'Named for Loch Earn in Perthshire, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'mchenry-md',
    name: 'McHenry',
    region: 'Maryland, USA',
    lng: -79.3578,
    lat: 39.5876,
    gaidhlig: 'Baile ’icEanruig',
    meaning: '"Settlement of McHenry" — Mac Eanruig, "son of Henry."',
    why_named: 'Named for James McHenry, signer of the US Constitution and Secretary of War (Scots-Irish origin).',
    founded: null,
    verified: false,
  },
  {
    id: 'midlothian-md',
    name: 'Midlothian',
    region: 'Maryland, USA',
    lng: -78.9886,
    lat: 39.5048,
    gaidhlig: 'Meadhon Lodainn',
    meaning: '"Meadhon Lodainn" — "the middle of Lothian."',
    why_named: 'Named for Midlothian, the historic county around Edinburgh.',
    founded: null,
    verified: false,
  },
  {
    id: 'montrose-md',
    name: 'Montrose',
    region: 'Maryland, USA',
    lng: -77.1175,
    lat: 39.0270,
    gaidhlig: 'Montrois',
    meaning: '"Montrois" — Gàidhlig rendering; the original "Monadh Rois" means "moor of the peninsula."',
    why_named: 'Named for Montrose in Angus, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'muirkirk-md',
    name: 'Muirkirk',
    region: 'Maryland, USA',
    lng: -76.8616,
    lat: 39.0468,
    gaidhlig: 'Eaglais an t-Sléibh',
    meaning: '"Eaglais an t-Sléibh" — "church of the moor" (Scots: muir = moor + kirk = church).',
    why_named: 'Named for Muirkirk in East Ayrshire, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'scotland-md',
    name: 'Scotland',
    region: 'Maryland, USA',
    lng: -76.4639,
    lat: 38.0936,
    gaidhlig: 'Alba',
    meaning: 'Alba is the Gàidhlig name for Scotland.',
    why_named: 'A diaspora tribute community in St. Mary\'s County.',
    founded: null,
    verified: false,
  },

  // Massachusetts
  {
    id: 'ashfield-ma',
    name: 'Ashfield',
    region: 'Massachusetts, USA',
    lng: -72.7681,
    lat: 42.5256,
    gaidhlig: 'Achadh an Uinnsinn',
    meaning: '"Achadh an Uinnsinn" — "the field of the ash tree."',
    why_named: 'Incorporated 1765; the English "Ashfield" rendered into Gàidhlig.',
    founded: '1765',
    verified: false,
  },
  {
    id: 'south-athol-ma',
    name: 'South Athol',
    region: 'Massachusetts, USA',
    lng: -72.21,
    lat: 42.55,
    gaidhlig: 'Athall a Deas',
    meaning: '"Athall a Deas" — "South Atholl" (a deas = of the south).',
    why_named: 'A village within the town of Athol; named for the Scottish region of Atholl.',
    founded: null,
    verified: false,
  },

  // Michigan
  {
    id: 'alba-mi',
    name: 'Alba',
    region: 'Michigan, USA',
    lng: -84.9711,
    lat: 44.9847,
    gaidhlig: 'Alba',
    meaning: 'Alba is the Gàidhlig name for Scotland.',
    why_named: 'A diaspora tribute — village in Antrim County.',
    founded: null,
    verified: false,
  },
  {
    id: 'argyle-mi',
    name: 'Argyle',
    region: 'Michigan, USA',
    lng: -83.0608,
    lat: 43.5994,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"Earra-Ghàidheal" — "the coastland of the Gaels."',
    why_named: 'Argyle Township in Sanilac County; named for Argyll, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'kinross-mi',
    name: 'Kinross',
    region: 'Michigan, USA',
    lng: -84.4936,
    lat: 46.2666,
    gaidhlig: 'Ceann Rois',
    meaning: '"Ceann Rois" — "head of the promontory" (ceann = head; ros = headland).',
    why_named: 'Named for Kinross in Scotland; village in Chippewa County.',
    founded: null,
    verified: false,
  },

  // ────────────────────────────────────────────────────────────────
  // Research follow-up batch (web-confirmed locations / etymology).
  // Added 2026-06-20.
  // ────────────────────────────────────────────────────────────────

  // Illinois
  {
    id: 'croft-il',
    name: 'Croft',
    region: 'Illinois, USA',
    lng: -89.71,
    lat: 40.05,
    gaidhlig: 'Croit',
    meaning: '"Croit" — "croft, smallholding."',
    why_named: 'Unincorporated community in Menard County, south of Middletown; named for the traditional Scottish croft.',
    founded: null,
    verified: false,
  },

  // Indiana
  {
    id: 'caledonia-in',
    name: 'Caledonia',
    region: 'Indiana, USA',
    lng: -87.45,
    lat: 39.06,
    gaidhlig: 'A’ Chailleann',
    meaning: 'Caledonia is the Latin name for Scotland; the Gàidhlig is Alba. "A’ Chailleann" is a poetic Gàidhlig rendering.',
    why_named: 'Former town in Cass Township, Sullivan County; extinct after extensive strip-mining. Post office 1902–1909.',
    founded: '1902',
    verified: false,
  },
  {
    id: 'campbelltown-in',
    name: 'Campbelltown',
    region: 'Indiana, USA',
    lng: -87.20,
    lat: 38.43,
    gaidhlig: 'Ceann Loch Chille Chiarain',
    meaning: '"Ceann Loch Chille Chiarain" — the Gàidhlig name for Campbeltown in Kintyre, Argyll ("head of Loch Kilkerran").',
    why_named: 'Unincorporated community in Patoka Township, Pike County; named for pioneer merchant Samuel Campbell.',
    founded: null,
    verified: false,
  },
  {
    id: 'iona-in',
    name: 'Iona',
    region: 'Indiana, USA',
    lng: -87.43,
    lat: 38.66,
    gaidhlig: 'Ì',
    meaning: '"Ì" — "the (yew) island"; the holy isle of Iona off Mull.',
    why_named: 'Populated place in Johnson Township, Knox County; named for the Scottish island of Iona.',
    founded: null,
    verified: false,
  },
  {
    id: 'perth-in',
    name: 'Perth',
    region: 'Indiana, USA',
    lng: -87.07,
    lat: 39.55,
    gaidhlig: 'Peairt',
    meaning: '"Peairt" — from a Pictish root meaning "wood" or "copse."',
    why_named: 'Unincorporated community in Dick Johnson Township, Clay County. Founded 1870 by Michael McMillan, named for Perth, Scotland, his birthplace; a coal-mining town that peaked around 400 residents in 1910.',
    founded: '1870',
    verified: false,
  },
  {
    id: 'kyle-in',
    name: 'Kyle',
    region: 'Indiana, USA',
    lng: -85.07,
    lat: 39.23,
    gaidhlig: 'Caol',
    meaning: '"Caol" — "narrow / strait."',
    why_named: 'Unincorporated community in Manchester Township, Dearborn County. Post office 1883–1904.',
    founded: '1883',
    verified: false,
  },

  // Iowa
  {
    id: 'dewar-ia',
    name: 'Dewar',
    region: 'Iowa, USA',
    lng: -92.18,
    lat: 42.59,
    gaidhlig: 'Deòir',
    meaning: '"Deòir" — the surname Dewar, from "deòraidh," "pilgrim / relic-keeper."',
    why_named: 'Unincorporated town in Poyner Township, Black Hawk County, NE of Waterloo. Platted 1888 (formerly Emert).',
    founded: '1888',
    verified: false,
  },
  {
    id: 'dumfries-ia',
    name: 'Dumfries',
    region: 'Iowa, USA',
    lng: -95.71,
    lat: 41.13,
    gaidhlig: 'Dùn Phrìs',
    meaning: '"Dùn Phrìs" — "fort of the thicket / copse."',
    why_named: 'Populated place in Lewis Township, Pottawattamie County; named for Dumfries in southern Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcmaster-creek-ia',
    name: 'McMaster Creek',
    region: 'Iowa, USA',
    lng: -95.9781,
    lat: 42.1591,
    gaidhlig: 'Allt ’ic a’ Mhaighstir',
    meaning: '"Allt ’ic a’ Mhaighstir" — "burn of MacMaster" (allt = stream / burn; Mac a’ Mhaighstir = son of the master).',
    why_named: 'Stream in Monona County, western Iowa; named for the MacMaster / McMaster family.',
    founded: null,
    verified: false,
  },

  // Maryland
  {
    id: 'gilmore-md',
    name: 'Gilmore',
    region: 'Maryland, USA',
    lng: -78.9883,
    lat: 39.5547,
    gaidhlig: 'Gille Moire',
    meaning: '"Gille Moire" — "servant of Mary" (gille = lad / servant; Moire = Mary).',
    why_named: 'Unincorporated community in Allegany County, in the Georges Creek valley between Midland and Lonaconing; named for a Gilmore family.',
    founded: null,
    verified: false,
  },
  {
    id: 'glen-burnie-md',
    name: 'Glen Burnie',
    region: 'Maryland, USA',
    lng: -76.6249,
    lat: 39.1626,
    gaidhlig: 'Gleann',
    meaning: '"Gleann" — "valley / glen."',
    why_named: 'Founded 1812 by district attorney Elias Glenn, who named his estate "Glennsburne" — evolving through "Glennsbourne Farm" to "Glenburnie." Now a suburb of Baltimore in Anne Arundel County.',
    founded: '1812',
    verified: false,
  },
  {
    id: 'greenock-md',
    name: 'Greenock',
    region: 'Maryland, USA',
    lng: -76.65,
    lat: 38.83,
    gaidhlig: 'Grianag',
    meaning: '"Grianag" — "sunny knoll / sunny bay" (grian = sun).',
    why_named: 'Hamlet in Anne Arundel County, near Lothian; named for Greenock on the Firth of Clyde, Scotland.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcalpine-md',
    name: 'McAlpine',
    region: 'Maryland, USA',
    lng: -76.7950,
    lat: 39.2727,
    gaidhlig: 'Baile ’icAilpinn',
    meaning: '"Settlement of MacAlpine" — Mac Ailpein, "son of Alpin" (the Pictish king-name).',
    why_named: 'Community in Howard County, just outside historic Ellicott City; notable for one of the few surviving postbellum country houses in the county.',
    founded: null,
    verified: false,
  },
  {
    id: 'mccleans-corner-md',
    name: 'McCleans Corner',
    region: 'Maryland, USA',
    lng: -76.1894,
    lat: 39.1982,
    gaidhlig: 'Oisinn ’ic’Ill’eathain',
    meaning: '"Oisinn ’ic’Ill’eathain" — "corner of MacLean" (oisinn = corner / angle; Mac ’Ill’Eathain = son of the servant of John).',
    why_named: 'Hamlet in Kent County on Maryland\'s Eastern Shore, near Chestertown; named for the MacLean / McLean family.',
    founded: null,
    verified: false,
  },
  {
    id: 'mcghiesport-md',
    name: 'McGhiesport',
    region: 'Maryland, USA',
    lng: -77.13,
    lat: 38.62,
    gaidhlig: 'Port ’icAoidh',
    meaning: '"Port of MacKay / McGhie" — Mac Aoidh, "son of Aodh (Hugh)."',
    why_named: 'Locality in Charles County (ZIP 20616), near Pomonkey Point and the hamlet of Fenwick.',
    founded: null,
    verified: false,
  },
  {
    id: 'mckay-beach-md',
    name: 'McKay Beach',
    region: 'Maryland, USA',
    lng: -76.55,
    lat: 38.13,
    gaidhlig: 'Tràigh ’icAoidh',
    meaning: '"Beach of MacKay" — tràigh = beach / shore; Mac Aoidh = son of Aodh.',
    why_named: 'Small Chesapeake Bay beach community in St. Mary\'s County, near Piney Point and Valley Lee.',
    founded: null,
    verified: false,
  },
  {
    id: 'scarff-md',
    name: 'Scarff',
    region: 'Maryland, USA',
    lng: -76.30,
    lat: 39.55,
    gaidhlig: 'Sgarbh',
    meaning: '"Sgarbh" — "cormorant" (the seabird).',
    why_named: 'Community in Harford County, NE Maryland.',
    founded: null,
    verified: false,
  },
  {
    id: 'st-andrews-md',
    name: 'St. Andrews',
    region: 'Maryland, USA',
    lng: -76.62,
    lat: 38.30,
    gaidhlig: 'Cill Rìmhinn',
    meaning: '"Cill Rìmhinn" — the Gàidhlig name for St Andrews in Fife ("church of Rignidh / the king\'s hill").',
    why_named: 'Community in St. Mary\'s County, off MD Route 4; named for St. Andrew\'s Episcopal Church (built 1767), part of a parish created by the Maryland Provincial Assembly in 1744.',
    founded: '1744',
    verified: false,
  },

  // Massachusetts
  {
    id: 'fife-brook-ma',
    name: 'Fife Brook',
    region: 'Massachusetts, USA',
    lng: -72.95,
    lat: 42.63,
    gaidhlig: 'Allt Fhìobha',
    meaning: '"Allt Fhìobha" — "burn of Fife" (allt = stream / burn; Fìobh = Fife, the Scottish region).',
    why_named: 'Tributary and dam on the Deerfield River in Charlemont, Berkshires; Fife Brook Dam built 1974.',
    founded: null,
    verified: false,
  },
  {
    id: 'renfrew-ma',
    name: 'Renfrew',
    region: 'Massachusetts, USA',
    lng: -73.113,
    lat: 42.638,
    gaidhlig: 'Rinn Friù',
    meaning: '"Rinn Friù" — "point of Friù"; Renfrew is from Cumbric "rhyn-frwd," "point of the current."',
    why_named: 'Populated place within Adams, Berkshire County; site of the 19th-century Renfrew Manufacturing Company, a major Berkshires wool mill.',
    founded: null,
    verified: false,
  },

  // Michigan
  {
    id: 'galloway-mi',
    name: 'Galloway',
    region: 'Michigan, USA',
    lng: -84.30,
    lat: 43.32,
    gaidhlig: 'Gall-Ghàidhealaibh',
    meaning: '"Gall-Ghàidhealaibh" — "the foreign Gaels" / "Norse-Gaels," the SW-Scottish region of Galloway.',
    why_named: 'Unincorporated community at the junction of Saginaw and Gratiot counties (Lakefield / Lafayette townships). Post office opened 1883 with first postmaster Richard Galloway.',
    founded: '1883',
    verified: false,
  },
  {
    id: 'guthrie-mi',
    name: 'Guthrie',
    region: 'Michigan, USA',
    lng: -84.06,
    lat: 42.30,
    gaidhlig: 'Gaothrach',
    meaning: '"Gaothrach" — "windy place" (gaoth = wind).',
    why_named: 'Populated place in Sylvan Township, Washtenaw County.',
    founded: null,
    verified: false,
  },
];
