// Seed list for the Gàidhlig diaspora place-name map.
//
// EVERY entry below should be reviewed by a native Gàidhlig speaker before
// publishing widely. The `verified` flag drives a small "unverified — help us
// confirm" badge in the side panel, so unverified entries are still useful but
// honestly flagged.
//
// Adding a place: drop a new object in the array. The map re-renders from this
// list — no other code changes needed.

export const PLACES = [
  {
    id: 'perth-ny',
    name: 'Perth',
    region: 'New York, USA',
    lng: -74.1707,
    lat: 43.0084,
    gaidhlig: 'Peairt',
    meaning: 'From a Pictish root meaning "wood" or "copse"; later associated with the thorn-bush.',
    why_named: 'Named after Perth, Scotland by Scottish settlers who arrived in the late 18th century.',
    founded: '1779',
    verified: false,
  },
  {
    id: 'broadalbin-ny',
    name: 'Broadalbin',
    region: 'New York, USA',
    lng: -74.1965,
    lat: 43.0640,
    gaidhlig: 'Bràghad Albann',
    meaning: '"The uplands of Alba (Scotland)" — the highland country.',
    why_named: 'Named after the Breadalbane region of Perthshire by emigrants from that area.',
    founded: '1815',
    verified: false,
  },
  {
    id: 'argyle-ny',
    name: 'Argyle',
    region: 'New York, USA',
    lng: -73.4948,
    lat: 43.2425,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"The coastland of the Gaels."',
    why_named: 'Named for Argyll, the ancestral kingdom of Dál Riata. Settled by Scottish Presbyterians in the 18th century.',
    founded: '1764',
    verified: false,
  },
  {
    id: 'scotia-ny',
    name: 'Scotia',
    region: 'New York, USA',
    lng: -73.9651,
    lat: 42.8267,
    gaidhlig: 'Alba',
    meaning: 'Scotia is the medieval Latin name for Scotland; the Gàidhlig name is Alba.',
    why_named: 'Named by Alexander Glen in 1658 in honour of his Scottish homeland.',
    founded: '1658',
    verified: false,
  },
  {
    id: 'inverness-ns',
    name: 'Inverness',
    region: 'Nova Scotia, Canada',
    lng: -61.2926,
    lat: 46.2336,
    gaidhlig: 'Inbhir Nis',
    meaning: '"Mouth of the River Ness."',
    why_named: 'Named for Inverness, the Highland capital, by Cape Breton settlers from the Scottish Highlands.',
    founded: '~1803',
    verified: false,
  },
  {
    id: 'glencoe-on',
    name: 'Glencoe',
    region: 'Ontario, Canada',
    lng: -81.7059,
    lat: 42.7501,
    gaidhlig: 'Gleann Comhann',
    meaning: '"The glen of the River Coe" — the glen of the 1692 massacre.',
    why_named: 'Settled in the 1830s by Highland Scots remembering the original Glen Coe.',
    founded: '~1836',
    verified: false,
  },
  {
    id: 'kilmarnock-va',
    name: 'Kilmarnock',
    region: 'Virginia, USA',
    lng: -76.3791,
    lat: 37.7115,
    gaidhlig: 'Cill Mheàrnaig',
    meaning: '"The church of (Saint) Marnoc" — a 7th-century Celtic saint.',
    why_named: 'Named for Kilmarnock in Ayrshire, Scotland.',
    founded: '~1780',
    verified: false,
  },
  {
    id: 'islay-township-on',
    name: 'Islay Township',
    region: 'Ontario, Canada',
    lng: -83.5,
    lat: 46.7,
    gaidhlig: 'Ìle',
    meaning: 'Pre-Celtic origin, uncertain; possibly meaning "swelling" or "island flank."',
    why_named: 'Named for the Hebridean island of Islay.',
    founded: null,
    verified: false,
  },
  {
    id: 'benbecula-ns',
    name: 'Benbecula',
    region: 'Nova Scotia, Canada',
    lng: -60.85,
    lat: 46.05,
    gaidhlig: 'Beinn nam Faoghla',
    meaning: '"Mountain of the fords" — referring to the tidal fords linking the islands.',
    why_named: 'Named after the Outer Hebridean island of Benbecula.',
    founded: null,
    verified: false,
  },
  {
    id: 'ballachulish-oh',
    name: 'Ballachulish',
    region: 'Ohio, USA',
    lng: -82.0,
    lat: 40.4,
    gaidhlig: "Baile a' Chaolais",
    meaning: '"Settlement of the narrows."',
    why_named: 'Named for Ballachulish in Argyllshire, at the mouth of Loch Leven.',
    founded: null,
    verified: false,
  },
];
