// Seed list for the Gàidhlig diaspora place-name map.
//
// EVERY entry below should be reviewed by a native Gàidhlig speaker before
// publishing widely. The `verified` flag drives a small "unverified — help us
// confirm" badge in the side panel, so unverified entries are still useful but
// honestly flagged.
//
// Adding a place: drop a new object in the array. The map re-renders from this
// list — no other code changes needed.

export const PLACES = [
  {
    id: 'perth-ny',
    name: 'Perth',
    region: 'New York, USA',
    lng: -74.1707,
    lat: 43.0084,
    gaidhlig: 'Peairt',
    meaning: 'From a Pictish root meaning "wood" or "copse"; later associated with the thorn-bush.',
    why_named: 'Named after Perth, Scotland by Scottish settlers who arrived in the late 18th century.',
    founded: '1779',
    verified: false,
  },
  {
    id: 'broadalbin-ny',
    name: 'Broadalbin',
    region: 'New York, USA',
    lng: -74.1965,
    lat: 43.0640,
    gaidhlig: 'Bràghad Albann',
    meaning: '"The uplands of Alba (Scotland)" — the highland country.',
    why_named: 'Named after the Breadalbane region of Perthshire by emigrants from that area.',
    founded: '1815',
    verified: false,
  },
  {
    id: 'argyle-ny',
    name: 'Argyle',
    region: 'New York, USA',
    lng: -73.4948,
    lat: 43.2425,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"The coastland of the Gaels."',
    why_named: 'Named for Argyll, the ancestral kingdom of Dál Riata. Settled by Scottish Presbyterians in the 18th century.',
    founded: '1764',
    verified: false,
  },
  {
    id: 'scotia-ny',
    name: 'Scotia',
    region: 'New York, USA',
    lng: -73.9651,
    lat: 42.8267,
    gaidhlig: 'Alba',
    meaning: 'Scotia is the medieval Latin name for Scotland; the Gàidhlig name is Alba.',
    why_named: 'Named by Alexander Glen in 1658 in honour of his Scottish homeland.',
    founded: '1658',
    verified: false,
  },
  {
    id: 'inverness-ns',
    name: 'Inverness',
    region: 'Nova Scotia, Canada',
    lng: -61.2926,
    lat: 46.2336,
    gaidhlig: 'Inbhir Nis',
    meaning: '"Mouth of the River Ness."',
    why_named: 'Named for Inverness, the Highland capital, by Cape Breton settlers from the Scottish Highlands.',
    founded: '~1803',
    verified: false,
  },
  {
    id: 'glencoe-on',
    name: 'Glencoe',
    region: 'Ontario, Canada',
    lng: -81.7059,
    lat: 42.7501,
    gaidhlig: 'Gleann Comhann',
    meaning: '"The glen of the River Coe" — the glen of the 1692 massacre.',
    why_named: 'Settled in the 1830s by Highland Scots remembering the original Glen Coe.',
    founded: '~1836',
    verified: false,
  },
  {
    id: 'kilmarnock-va',
    name: 'Kilmarnock',
    region: 'Virginia, USA',
    lng: -76.3791,
    lat: 37.7115,
    gaidhlig: 'Cill Mheàrnaig',
    meaning: '"The church of (Saint) Marnoc" — a 7th-century Celtic saint.',
    why_named: 'Named for Kilmarnock in Ayrshire, Scotland.',
    founded: '~1780',
    verified: false,
  },
  {
    id: 'islay-township-on',
    name: 'Islay Township',
    region: 'Ontario, Canada',
    lng: -83.5,
    lat: 46.7,
    gaidhlig: 'Ìle',
    meaning: 'Pre-Celtic origin, uncertain; possibly meaning "swelling" or "island flank."',
    why_named: 'Named for the Hebridean island of Islay.',
    founded: null,
    verified: false,
  },
  {
    id: 'benbecula-ns',
    name: 'Benbecula',
    region: 'Nova Scotia, Canada',
    lng: -60.85,
    lat: 46.05,
    gaidhlig: 'Beinn nam Faoghla',
    meaning: '"Mountain of the fords" — referring to the tidal fords linking the islands.',
    why_named: 'Named after the Outer Hebridean island of Benbecula.',
    founded: null,
    verified: false,
  },
  {
    id: 'ballachulish-oh',
    name: 'Ballachulish',
    region: 'Ohio, USA',
    lng: -82.0,
    lat: 40.4,
    gaidhlig: "Baile a' Chaolais",
    meaning: '"Settlement of the narrows."',
    why_named: 'Named for Ballachulish in Argyllshire, at the mouth of Loch Leven.',
    founded: null,
    verified: false,
  },
  {
    id: 'argyle-wi',
    name: 'Argyle',
    region: 'Wisconsin, USA',
    lng: -89.8559,
    lat: 42.7027,
    gaidhlig: 'Earra-Ghàidheal',
    meaning: '"The coastland of the Gaels."',
    why_named: 'Settled in the 1840s by Scottish lead-miners moving up from the Galena district; named for Argyll.',
    founded: '~1844',
    verified: false,
  },
  {
    id: 'caledonia-wi',
    name: 'Caledonia',
    region: 'Wisconsin, USA',
    lng: -87.8786,
    lat: 42.8077,
    gaidhlig: 'Alba',
    meaning: 'Caledonia is the Latin name the Romans gave to Scotland; the Gàidhlig name for the country is Alba.',
    why_named: 'A settlers\' tribute to the Scottish homeland — one of several Caledonias scattered across the diaspora.',
    founded: '1839',
    verified: false,
  },
  {
    id: 'glencoe-mn',
    name: 'Glencoe',
    region: 'Minnesota, USA',
    lng: -94.1517,
    lat: 44.7691,
    gaidhlig: 'Gleann Comhann',
    meaning: '"The glen of the River Coe" — the glen of the 1692 massacre.',
    why_named: 'Named in 1855 for Glen Coe in Scotland by founding settler Martin McLeod.',
    founded: '1855',
    verified: false,
  },
  {
    id: 'inverness-ca',
    name: 'Inverness',
    region: 'California, USA',
    lng: -122.8580,
    lat: 38.1010,
    gaidhlig: 'Inbhir Nis',
    meaning: '"Mouth of the River Ness."',
    why_named: 'Founded on Tomales Bay in 1889 by James Shafter, a Scottish-American attorney who said the landscape reminded him of the Highlands.',
    founded: '1889',
    verified: false,
  },
  {
    id: 'glengarry-on',
    name: 'Glengarry',
    region: 'Ontario, Canada',
    lng: -74.6400,
    lat: 45.3800,
    gaidhlig: 'Gleann Garadh',
    meaning: '"The glen of the River Garry."',
    why_named: 'Named for Glen Garry in Inverness-shire, the seat of Clann Dòmhnaill of Glengarry. Settled from 1784 onward by Highland Loyalists who came up from the Mohawk Valley, then by waves of direct emigrants from Knoydart and Glengarry itself — the densest Gàidhlig-speaking county in 19th-century Canada.',
    founded: '1784',
    verified: false,
  },
  {
    id: 'iona-ns',
    name: 'Iona',
    region: 'Nova Scotia, Canada',
    lng: -60.7937,
    lat: 45.9603,
    gaidhlig: 'Ì (Ì Chaluim Chille)',
    meaning: '"The (yew) island" — the second form means "Iona of Columba" after the saint.',
    why_named: "Named for the holy isle of Iona off Mull, the cradle of Gaelic Christianity. Sits on the Bras d'Or Lake at the heart of Cape Breton's Gàidhlig-speaking belt; home to the Highland Village Museum / Baile nan Gàidheal.",
    founded: '~1820s',
    verified: false,
  },
];
