// robots.txt — generated by Next.js App Router.
// Let crawlers in (the pre-launch gate was hiding real content from Google,
// which is why "global ceilidh" searches surfaced the Live365 station page
// instead of us). Only genuinely private / non-content routes are disallowed.

export default function robots() {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/api/',
        '/contribute/',   // personal, tokened upload links — noindex
        '/welcome',       // auth-gated onboarding
        '/rooms/',        // invite-only
        '/sign-in',
        '/sign-up',
      ],
    },
    sitemap: 'https://globalceilidh.com/sitemap.xml',
    host: 'https://globalceilidh.com',
  };
}
