// sitemap.xml — generated by Next.js App Router. Lists the public, crawlable
// surfaces so Google indexes the real GlobalCeilidh site (front door + radio
// + sruth + the map) rather than a thin placeholder.

const BASE = 'https://globalceilidh.com';

export default function sitemap() {
  const now = new Date();
  const routes = [
    { path: '/', priority: 1.0, changeFrequency: 'weekly' },
    { path: '/radio', priority: 0.9, changeFrequency: 'daily' },
    { path: '/sruth', priority: 0.9, changeFrequency: 'weekly' },
    { path: '/sruth/archive', priority: 0.7, changeFrequency: 'weekly' },
    { path: '/saoghal', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/saoghal/archives', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/saoghal/archives/Gael_1', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/feisean', priority: 0.6, changeFrequency: 'weekly' },
  ];

  return routes.map((r) => ({
    url: `${BASE}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
