// app/api/radio/artist-info/route.js
// Feeds the /radio INFO overlay. Resolves the now-playing artist + song to the
// grounded-Gemini copy in gc_artists / gc_radio_songs (generated by the
// sruth-backend radio_bios worker from the playlog). Read-only, public.
//
// GD is only surfaced once gd_status === 'approved' (Lewis/Joe); until then the
// client falls back to EN even in Gàidhlig mode — the copy still ships, the
// Gàidhlig just waits for the stamp.

import { supabaseAdmin } from '../../../../lib/supabase';

// Must match the Python _norm() in sruth-backend/app/workers/radio_bios.py so a
// profile generated from the playlog resolves back to the played name.
function norm(s) {
  return (s || '')
    .toString()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ');
}

const ARTIST_COLS =
  'slug,name,origin,bio_en,bio_gd,sound_en,sound_gd,links,image_url,confidence,gd_status,status';

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const artist = searchParams.get('artist') || '';
  const title = searchParams.get('title') || '';
  const an = norm(artist);
  if (!an) return Response.json({ ok: true, artist: null, song: null });

  let art = null;
  try {
    const { data } = await supabaseAdmin
      .from('gc_artists')
      .select(ARTIST_COLS)
      .eq('name_norm', an)
      .eq('status', 'published')
      .limit(1);
    art = (data && data[0]) || null;

    // Fall back to an alias match (Gemini may have canonicalised the name).
    if (!art && artist) {
      const { data: al } = await supabaseAdmin
        .from('gc_artists')
        .select(ARTIST_COLS)
        .contains('aliases', [artist])
        .eq('status', 'published')
        .limit(1);
      art = (al && al[0]) || null;
    }
  } catch {
    /* table may be mid-populate; treat as no data */
  }

  let song = null;
  if (title) {
    const tn = norm(title);
    try {
      const { data } = await supabaseAdmin
        .from('gc_radio_songs')
        .select('title,blurb_en,blurb_gd,gd_status')
        .eq('artist_norm', an)
        .eq('title_norm', tn)
        .limit(1);
      song = (data && data[0]) || null;
    } catch {
      /* no song blurb yet */
    }
  }

  return Response.json(
    { ok: true, artist: art, song, nowTitle: title || null },
    { headers: { 'Cache-Control': 's-maxage=30, stale-while-revalidate=60' } },
  );
}
