// app/artists/[slug]/page.js
// Public Global Ceilidh artist page — the destination for the /radio INFO
// "Full profile" CTA and a crawlable landing surface for radio traffic.
// Reads the grounded-Gemini profile from gc_artists (generated by the
// sruth-backend radio_bios worker) + the artist's song blurbs. ISR.
//
// Renders English for now: the Gàidhlig fields exist but stay gated behind
// gd_status until Lewis/Joe sign off, so we don't publish unstamped Gàidhlig.

import { notFound } from 'next/navigation';
import { supabaseAdmin } from '../../../lib/supabase';

export const revalidate = 300; // 5 min

async function loadArtist(slug) {
  const { data } = await supabaseAdmin
    .from('gc_artists')
    .select('*')
    .eq('slug', slug)
    .eq('status', 'published')
    .limit(1);
  return (data && data[0]) || null;
}

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const a = await loadArtist(slug);
  if (!a) return { title: 'Artist · Global Ceilidh' };
  return {
    title: `${a.name} · Global Ceilidh`,
    description: (a.bio_en || '').slice(0, 155),
  };
}

export default async function ArtistPage({ params }) {
  const { slug } = await params;
  const a = await loadArtist(slug);
  if (!a) notFound();

  const { data: songs } = await supabaseAdmin
    .from('gc_radio_songs')
    .select('title,blurb_en')
    .eq('artist_id', a.id)
    .order('title');

  const linkOrder = ['website', 'spotify', 'youtube', 'instagram', 'facebook'];
  const links = a.links || {};

  return (
    <main style={S.page}>
      <div style={S.wrap}>
        <a href="/radio" style={S.back}>← Global Ceilidh Radio</a>

        <header style={S.header}>
          <h1 style={S.name}>{a.name}</h1>
          {a.origin && <p style={S.origin}>{a.origin}</p>}
        </header>

        {a.bio_en && <p style={S.bio}>{a.bio_en}</p>}
        {a.sound_en && <p style={S.sound}>{a.sound_en}</p>}

        {linkOrder.some((k) => links[k]) && (
          <div style={S.links}>
            {linkOrder.filter((k) => links[k]).map((k) => (
              <a key={k} href={links[k]} target="_blank" rel="noopener noreferrer" style={S.chip}>
                {k[0].toUpperCase() + k.slice(1)}
              </a>
            ))}
          </div>
        )}

        {Array.isArray(songs) && songs.length > 0 && (
          <section style={S.songs}>
            <h2 style={S.songsHead}>On Global Ceilidh Radio</h2>
            {songs.map((s, i) => (
              <div key={i} style={S.song}>
                <div style={S.songTitle}>{s.title}</div>
                {s.blurb_en && <p style={S.songBlurb}>{s.blurb_en}</p>}
              </div>
            ))}
          </section>
        )}

        <div style={S.footer}>
          <a href="/sruth" style={S.cta}>Get the Sruth newsletter</a>
          <a href="/AnTonn" style={S.ctaGhost}>Explore An Tonn</a>
        </div>

        <p style={S.disclaimer}>
          Profile compiled by Global Ceilidh from public sources. Something to correct?{' '}
          <a href="/contact" style={S.discLink}>Let us know</a>.
        </p>
      </div>
    </main>
  );
}

const CREAM = '#F2ECDC';
const GOLD = '#C9A047';
const BEBAS = 'var(--font-bebas-neue), "Bebas Neue", Impact, sans-serif';
const SANS = 'var(--font-ibm-plex-sans), "IBM Plex Sans", system-ui, sans-serif';
const MONO = '"IBM Plex Mono", Menlo, monospace';

const S = {
  page: { minHeight: '100dvh', background: '#060B14', color: CREAM, padding: '48px 20px 80px' },
  wrap: { maxWidth: 720, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 18 },
  back: { fontFamily: MONO, fontSize: 12, letterSpacing: 1, color: GOLD, textDecoration: 'none' },
  header: { marginTop: 8 },
  name: { fontFamily: BEBAS, fontSize: 'clamp(44px, 9vw, 72px)', letterSpacing: '0.02em', margin: 0, lineHeight: 0.98, color: '#FFFFFF' },
  origin: { fontFamily: MONO, fontSize: 12.5, letterSpacing: 1.6, textTransform: 'uppercase', color: GOLD, margin: '10px 0 0' },
  bio: { fontFamily: SANS, fontSize: 17, lineHeight: 1.7, color: 'rgba(242,236,220,0.92)', margin: 0 },
  sound: { fontFamily: SANS, fontSize: 15.5, lineHeight: 1.7, color: 'rgba(242,236,220,0.68)', margin: 0 },
  links: { display: 'flex', flexWrap: 'wrap', gap: 10, marginTop: 4 },
  chip: {
    fontFamily: MONO, fontSize: 12, letterSpacing: 0.5, color: CREAM, textDecoration: 'none',
    padding: '8px 14px', borderRadius: 999, border: '1px solid rgba(242,236,220,0.22)', background: 'rgba(255,255,255,0.04)',
  },
  songs: { marginTop: 18, borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: 22, display: 'flex', flexDirection: 'column', gap: 16 },
  songsHead: { fontFamily: MONO, fontSize: 12, letterSpacing: 2, textTransform: 'uppercase', color: 'rgba(242,236,220,0.55)', margin: 0 },
  song: { display: 'flex', flexDirection: 'column', gap: 3 },
  songTitle: { fontFamily: 'Fraunces, Georgia, serif', fontStyle: 'italic', fontSize: 18, color: CREAM },
  songBlurb: { fontFamily: SANS, fontSize: 14.5, lineHeight: 1.6, color: 'rgba(242,236,220,0.72)', margin: 0 },
  footer: { display: 'flex', flexWrap: 'wrap', gap: 12, marginTop: 26 },
  cta: {
    fontFamily: BEBAS, fontSize: 18, letterSpacing: '0.06em', textTransform: 'uppercase',
    color: '#0A1220', background: GOLD, textDecoration: 'none', padding: '12px 22px', borderRadius: 999,
  },
  ctaGhost: {
    fontFamily: BEBAS, fontSize: 18, letterSpacing: '0.06em', textTransform: 'uppercase',
    color: CREAM, background: 'transparent', textDecoration: 'none', padding: '12px 22px',
    borderRadius: 999, border: '1px solid rgba(242,236,220,0.28)',
  },
  disclaimer: { fontFamily: MONO, fontSize: 10.5, letterSpacing: 0.8, color: 'rgba(242,236,220,0.4)', marginTop: 30 },
  discLink: { color: 'rgba(242,236,220,0.6)' },
};
